// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXqQqjK6R8TS8TOV4F7FsAH0W24w6zucE',
    appId: '1:643438587690:web:3877b87bf84fdd4c913853',
    messagingSenderId: '643438587690',
    projectId: 'msp-hosting',
    authDomain: 'msp-hosting.firebaseapp.com',
    storageBucket: 'msp-hosting.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC95Vegk1kFBrb9Yz1-a-_9GD0jefhwGrg',
    appId: '1:643438587690:android:ba334108cc9427e3913853',
    messagingSenderId: '643438587690',
    projectId: 'msp-hosting',
    storageBucket: 'msp-hosting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyC__pAVS_RoxDkqxKGkzQPPElwxNM5jE',
    appId: '1:643438587690:ios:e203aaff0878b4d5913853',
    messagingSenderId: '643438587690',
    projectId: 'msp-hosting',
    storageBucket: 'msp-hosting.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );
}
